spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/oauth
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: never
server:
  port: 8081